Use zero-based indexes when referrring to option indexes.
pgbackrest/pgbackrest pull request #1207
Opened 2020-10-21 12:38 UTC by dwsteele

There were a number of places in the code where "hostId" was used, but hostId is just the option group index + 1 so this led to a lot of +1 and -1 to convert the id to an index and vice versa.

Instead just use the zero based index wherever possible. This is pretty much everywhere except when the host-id option is read or set, or where a message is being formatted for the user.

Also fix a bug in protocolRemoteParam() where remotes spawned from the main process could get process ids that were not 0. Only the locals should spawn remotes with process id > 0. This seems to have been harmless since the process id is only a label, but it could be confusing when debugging.

2020-10-23 17:20 UTC, cmwshang requested changes
Review complete

2020-10-24 14:25 UTC, dwsteele commented on src/protocol/helper.c
>      if (cfgOptionTest(optHostPort))
Yeah, this was an ill-advised merge from the next commit. Ironically I was trying to make things simpler. I'll just revert and we'll try again when it makes more sense.

2020-10-24 14:25 UTC, dwsteele commented on src/protocol/helper.c
> +    unsigned int optConfig = isRepo ? cfgOptRepoHostConfig : cfgOptPgHostConfig;
Same as above.

2020-10-24 14:27 UTC, dwsteele commented on src/protocol/helper.c
> +                cfgOptionStr(cfgOptCmdSsh), protocolRemoteParam(protocolStorageType, hostIdx),
At this point optHostIdx and hostIdx have become the same thing so I'll just replace optHostIdx with hostIdx.

2020-10-24 14:32 UTC, dwsteele commented on src/command/check/common.c
> -        unsigned int pgPath = cfgOptPgPath + (dbIdx - 1);
Again, I was trying to make less churn with the next commit, but the changes don't make much sense in this context. I reverted and we'll revisit in the next commit.

2020-10-26 12:45 UTC, cmwshang approved these changes

2020-10-26 14:25 UTC, merged