Utilize httpUrlNewParseP to parse endpoint in s3/azure helpers
pgbackrest/pgbackrest pull request #1591
Opened 2021-12-09 14:49 UTC by jreidthompson

Utilize httpUrlNewParseP to parse endpoint and port from the url in the s3 and azure helpers to avoid issues where protocol was not expected to be part of the url.

https://github.com/pgbackrest/pgbackrest/issues/1560

2021-12-14 15:01 UTC, dwsteele requested changes
This looks pretty good, but I'd like to see some more tests updated with the new format.

2021-12-15 23:54 UTC, jreidthompson commented on src/storage/s3/helper.c
> +    const String *host = NULL;
Corrected 79941de0345564d4e535031290832592e93eac25

2021-12-15 23:57 UTC, jreidthompson commented on src/storage/azure/helper.c
> +    if (cfgOptionIdxSource(cfgOptRepoStoragePort, repoIdx) != cfgSourceDefault)
Corrected c9a899338bd2fcfc2c8db319a117a446ace9bb01


Added various uri / uristyle tests also
177a12eca5af262d9c9a4db690c1fa78f094d642

2021-12-16 15:13 UTC, dwsteele approved these changes
Some formatting/comment updates in 644619a76f1bf39b21/5e35eb77cf2ba0b7c4.

2021-12-16 15:30 UTC, merged