Add a parameter to explicitly specify the size of the WAL segment.
pgbackrest/pgbackrest pull request #2303
Opened 2024-03-15 11:53 UTC by KnightMurloc

Before PostgreSQL 11, alternative WAL segment sizes can be selected at compile-time, for example, 64MB. While compile-time settings are generally not well tested by the core, some established forks, such as Greenplum, use them.
This patch adds a parameter that allows explicitly specify the expected size of the WAL segment. Which can be useful for backup forks whose base version of Postgres is less than 11.

2024-03-15 11:53 UTC, KnightMurloc commented
@dwsteele, you asked to make PRs from personal forks, not from the company's one. My team lead says that we cannot use personal forks, because there is a possibility of losing access to the PR in case the author of the PR is unavailable (has resigned, gone on vacation, on sick leave, etc.). Therefore, the company policy requires making PRs from the corporate fork. As a solution, if you want to make cosmetic changes, you can form final commit with your changes in the integration branch, and then close the PR.

2024-03-16 05:31 UTC, dwsteele commented
I'm not too excited about adding an option for this. If we are going to let people bypass this then I think it makes more sense to simply remove the constraint at https://github.com/pgbackrest/pgbackrest/blob/release/2.50/src/postgres/interface.c#L176.

> you asked to make PRs from personal forks, not from the company's one

You and your colleagues are making valuable contributions so I'm not going to make a big fuss. I still prefer to merge the commit rather than closing it so we'll just continue what we've been doing.

2024-03-18 04:15 UTC, KnightMurloc commented
That is, would you prefer the option without checking for Postgres < 11 that the size of the WAL segment is the default, leaving only the check that the value is valid?

2024-03-18 05:41 UTC, dwsteele commented
> That is, would you prefer the option without checking for Postgres < 11 that the size of the WAL segment is the default, leaving only the check that the value is valid?

I can't quite parse these sentence, but I think so? All versions <= 11 are EOL so I'm OK with just removing the constraint on the value being default, which should just mean removing that check and adjusting the test.

2024-06-07 09:07 UTC, KnightMurloc commented
@dwsteele Hello, I would like to know the status of this PR. Do I need to make any other edits?

2024-06-07 23:35 UTC, dwsteele commented on src/command/archive/common.c
> +    ASSERT(pgWalSegmentSizeValid(pgVersion, walSegmentSize));
I'd prefer to just remove this assert().

2024-06-07 23:38 UTC, dwsteele requested changes
Sorry, I didn't see that this had been updated. I'd like to keep the implementation simpler since we are dealing with EOL versions of Postgres. See comments.

2024-06-07 23:38 UTC, dwsteele commented on src/postgres/interface.c
> +
I don't think it is worth adding this exception for EOL versions of PostgreSQL. If somebody somehow convinces older versions of PostgreSQL to use large WAL segments sizes, then that is on them.

2024-06-07 23:38 UTC, dwsteele commented on src/postgres/interface.c
> -
I think we should just be removing this and then updating tests.

2024-06-10 03:29 UTC, dwsteele approved these changes
I renamed HRN_PG_WAL_SEGMENT_SIZE_DEFAULT in c57496a483b but otherwise looks good to me. Please pull https://github.com/dwsteele/pgbackrest/tree/ADBDEV-4788-ci with these changes and the release note.

2024-06-11 00:25 UTC, merged

2024-06-11 01:07 UTC, dwsteele commented
Updated to 2cf5a46663d to fix commit message.